server:
  port: 8081
  
security:
  basic:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahulkarale/Spring-CloudConfig.git
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/rahulkarale/springcloudeconfig-prf.git
              search-paths:
                - 'station*'
 

eureka:
  instance:
      hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  