server:
  port: 8081

spring:
  datasource:
    username:
      postgres
    url:
      jdbc:postgresql://localhost/testdb
    password: 90495681
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
      hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/